import { Car, CustomerReview, Certificate, EnhancedCar, CarCategory, Bus, EnhancedBus } from "./types";

export interface Location {
  id: string;
  name: string;
  extraCharge: number;
}

export interface AdditionalService {
  id: string;
  name: string;
  price: number;
  description: string;
}

// Enhanced cars data with new fields
export const enhancedCars: EnhancedCar[] = [
  {
    id: "1",
    brand: "Skoda",
    model: "Octavia",
    year: 2021,
    class: "Ekonom",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.5L",
    seats: 5,
    dailyPrice: 80,
    weeklyPrice: 70,
    monthlyPrice: 60,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img9.jpeg",
    ],
    features: ["Kondisioner", "GPS Naviqasiya", "Bluetooth", "USB Port"],
    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 85,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/skoda/img9.jpeg",
    ],
    specifications: {
      engine: "2.0L 4-Cylinder",
      horsepower: 147,
      acceleration: "0-100 km/h in 9.2s",
      topSpeed: 190,
      fuelConsumption: "5L/100km",
    },
  },
  {
    id: "2",
    brand: "Toyota",
    model: "Corolla",
    year: 2025,
    class: "Ekonom",
    fuelType: "Hybrid",
    transmission: "Avtomat",
    engineSize: "1.8L",
    seats: 5,
    dailyPrice: 90,
    weeklyPrice: 80,
    monthlyPrice: 65,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img9.jpeg",

    ],
    features: [
      "Premium Dəri Oturacaqlar",
      "Panorama Dam",
      "Adaptiv Kruiz Kontrol",
      "Wireless Charging",
    ],
    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 92,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorolla/img9.jpeg",
    ],
    specifications: {
      engine: "2.5L 4-Cylinder",
      horsepower: 203,
      acceleration: "0-100 km/h in 7.8s",
      topSpeed: 210,
      fuelConsumption: "7.2L/100km",
    },
  },
  {
    id: "3",
    brand: "BMW",
    model: "X5",
    year: 2023,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "3.0L",
    seats: 7,
    dailyPrice: 350,
    weeklyPrice: 320,
    monthlyPrice: 300,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img5.jpeg",
    
    ],
    features: ["4WD", "Premium Audio", "Heated Seats", "Advanced Safety"],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Business",],
    popularity: 88,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/X5/img5.jpeg",
    ],
    specifications: {
      engine: "3.0L Twin-Turbo I6",
      horsepower: 350,
      acceleration: "0-100 km/h in 5.8s",
      topSpeed: 243,
      fuelConsumption: "9.1L/100km",
    },
  },
  {
    id: "4",
    brand: "Changan ",
    model: " Nevo A05",
    year: 2024,
    class: "Ekonom",
    fuelType: "Hybrid",
    transmission: "Avtomat",
    engineSize: "1.5L",
    seats: 5,
    dailyPrice: 80,
    weeklyPrice: 70,
    monthlyPrice: 60,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img9.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img10.jpeg",

    ],
    features: [
      "Panorama Şüşə Dam",
      "Arxa Park Kamerası",
      "Multimedya və Bluetooth Bağlantısı",
      "Led Gündüz İşıqları və LED Arxa İşıqlandırma",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 95,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img9.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/changanNevo05/img10.jpeg",
    ],
    specifications: {
      engine: "1.5 Hybrid",
      horsepower: 255,
      acceleration: "0-100 km/h in 6.6s",
      topSpeed: 190,
      fuelConsumption: "3.0L/100km",
    },
  },
  {
    id: "5",
    brand: "Mercedes",
    model: "E220 Cabrio",
    year: 2019,
    class: "Sedan",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.2L TDI",
    seats: 5,
    dailyPrice: 350,
    weeklyPrice: 300,
    monthlyPrice: 250,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img8.jpeg",

    ],
    features: [
      "Harman Kardon Premium Səs Sistemi",
      "Full LED Matrix Faralar",
      "Multikontur Ön Oturacaqlar Ventilyasiya ilə",
      "Heads-Up Display (HUD)",
    ],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Lüks","Sedan"],
    popularity: 78,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/e220mercedes/img8.jpeg",
    ],
    specifications: {
      engine: "2.2L TDI Diesel",
      horsepower: 150,
      acceleration: "0-100 km/h in 8.7s",
      topSpeed: 210,
      fuelConsumption: "4.8L/100km",
    },
  },
  {
    id: "6",
    brand: "Kia",
    model: "Rio",
    year: 2022,
    class: "Ekonom",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.6L",
    seats: 5,
    dailyPrice: 65,
    weeklyPrice: 60,
    monthlyPrice: 45,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img7.jpeg",
    ],
    features: [
      "Arxa Park Sensorları",
      "Kondisioner (Manual İdarəetmə)",
      "Bluetooth və USB Bağlantısı",
      "Elektrik Ön Şüşə Qaldırıcılar",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiaRio/img7.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "7",
    brand: "BYD",
    model: "Qin Plus",
    year: 2024,
    class: "Ekonom",
    fuelType: "Hibrid",
    transmission: "Avtomat",
    engineSize: "1.5L",
    seats: 5,
    dailyPrice: 70,
    weeklyPrice: 60,
    monthlyPrice: 50,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img9.jpeg",

    ],
    features: [
      "Rəqəmsal Sürət Paneli",
      "Çoxfunksiyalı Sükan",
      "Kameralı Arxa Görünüş",
      "Avtomatik İşıqlandırma",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/BydQinPlus/img9.jpeg",
    ],
    specifications: {
      engine: "1.5L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "8",
    brand: "Volkswagen",
    model: "Polo",
    year: 2022,
    class: "Ekonom",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.6L",
    seats: 5,
    dailyPrice: 65,
    weeklyPrice: 60,
    monthlyPrice: 50,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img7.jpeg",

    ],
    features: [
      "Əl Kondisioneri",
      "USB və Bluetooth Bağlantısı",
      "Arxa Park Sensorları",
      "Elektrik Ön və Arxa Şüşə Qaldırıcılar",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/volksvagenPolo/img7.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "9",
    brand: "Toyota",
    model: "RAV4",
    year: 2024,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.5L",
    seats: 6,
    dailyPrice: 140,
    weeklyPrice: 125,
    monthlyPrice: 100,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img9.jpeg",

    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img7.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img8.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaRav4/img9.jpeg",

    ],
    specifications: {
      engine: "2.5L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "10",
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2025,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.0L",
    seats: 6,
    dailyPrice: 110,
    weeklyPrice: 100,
    monthlyPrice: 85,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img6.jpeg",

    ],
    features: [
      "Tək Zonlu Avtomatik Klima",
      "Arxa Park Kamerası",
      "Bluetooth / USB Bağlantısı",
      "LED Gündüz Işıqlandırması",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/toyotaCorollaCross/img6.jpeg",
    ],
    specifications: {
      engine: "2.0L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "12",
    brand: "Fiat",
    model: "Doblo",
    year: 2020,
    class: "Van",
    fuelType: "Benzin",
    transmission: "Mexaniki",
    engineSize: "1.4L",
    seats: 2,
    dailyPrice: 65,
    weeklyPrice: 55,
    monthlyPrice: 45,
    deposit: 200,
    image:       "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img7.jpeg",

    ],
    features: [
      "Bluetooth Connectivity",
      "Keyless Entry",
      "Cruise Control",
      "Back-Up Camera",
    ],

    rules: {
      minimumAge: 23,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Minivan","Hatchback"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/FiatDoblo/img7.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "13",
    brand: "Toyota",
    model: "Land Cruiser",
    year: 2017,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "4L",
    seats: 7,
    dailyPrice: 230,
    weeklyPrice: 200,
    monthlyPrice: 170,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img1.jpeg",
    images: [
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img1.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img2.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img3.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img4.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img5.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img6.jpeg",
     "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img7.jpeg",
      
 

    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 23,
      drivingExperience: 1,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img6.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/LandCruser/img7.jpeg",
    ],
    specifications: {
      engine: "4L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "15",
    brand: "Toyota",
    model: "Land Cruiser Prado",
    year: 2015,
    class: "SUV ",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.7L",
    seats: 7,
    dailyPrice: 170,
    weeklyPrice: 155,
    monthlyPrice: 140,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img6.jpeg",


    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landcruserprado/img6.jpeg",
    ],
    specifications: {
      engine: "2.7L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "16",
    brand: "Land Rover ",
    model: "Range Rover",
    year: 2019,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "3.0L",
    seats: 5,
    dailyPrice: 450,
    weeklyPrice: 400,
    monthlyPrice: 250,
    deposit: 200,
    image:  "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img6.jpeg",
   
    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Lüks", "SUV", "Biznes"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/rangerover/img6.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "17",
    brand: "Mercedes",
    model: "V 250",
    year: 2015,
    class: "Ekonom",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.2L",
    seats: 7,
    dailyPrice: 250,
    weeklyPrice: 230,
    monthlyPrice: 200,
    deposit: 200,
    image:   "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img1.jpeg",
    images: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img6.jpeg",

    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 23,
      drivingExperience: 1,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Minivan","Hatchback"],
    popularity: 82,
    availability: true,
    gallery: [
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img1.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img2.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img3.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img4.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img5.jpeg",
      "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/mercedesV25/img6.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "18",
    brand: "Hyundai",
    model: "Accent",
    year: 2022,
    class: "Ekonom",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.6L",
    seats: 5,
    dailyPrice: 65,
    weeklyPrice: 55,
    monthlyPrice: 50,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img5.jpeg",
    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 21,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Ekonom","Sedan"],
    popularity: 82,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/hyundaiaccent/img5.jpeg",
    ],
    specifications: {
      engine: "1.6L 4-Cylinder",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 195,
      fuelConsumption: "8.2L/100km",
    },
  },
  {
    id: "19",
    brand: "BMW ",
    model: "i7",
    year: 2023,
    class: "Biznes",
    fuelType: "electric",
    transmission: "Avtomat",
    engineSize: "0",
    seats: 5,
    dailyPrice: 850,
    weeklyPrice: 800,
    monthlyPrice: 700,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img7.jpeg",

    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 24,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Business","Sedan"],
    popularity: 82,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/bmwi7/img7.jpeg",
    ],
    specifications: {
      engine: "0L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 250,
      fuelConsumption: "4.2L/100km",
    },
  },
  {
    id: "20",
    brand: "Toyota ",
    model: "Camry",
    year: 2023,
    class: "Biznes",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.5",
    seats: 5,
    dailyPrice: 120,
    weeklyPrice: 100,
    monthlyPrice: 70,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img7.jpeg",

    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 24,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Business","Sedan"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2024/img7.jpeg",
    ],
    specifications: {
      engine: "2.5L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 250,
      fuelConsumption: "4.2L/100km",
    },
  },
  {
    id: "21",
    brand: "Toyota ",
    model: "Camry",
    year: 2024,
    class: "Biznes",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.5",
    seats: 5,
    dailyPrice: 140,
    weeklyPrice: 110,
    monthlyPrice: 80,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img6.jpg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img6.jpg",
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img7.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img8.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img9.jpeg'





    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 24,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Business","Sedan"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img6.jpg",
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img7.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img8.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/camry2025/img9.jpeg'
    ],
    specifications: {
      engine: "2.5L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 250,
      fuelConsumption: "4.2L/100km",
    },
  },
  {
    id: "22",
    brand: "Chevrolet ",
    model: "Spark",
    year: 2023,
    class: "Biznes",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.4",
    seats: 4,
    dailyPrice: 40,
    weeklyPrice: 30,
    monthlyPrice: 20,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img7.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img8.jpeg",



    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Hatchback","Economy"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img5.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img6.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img7.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/chevroletspark/img8.jpeg",
    ],
    specifications: {
      engine: "1.4L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 100,
      fuelConsumption: "1.4L/100km",
    },
  },
//   {
//     id: "23",
//     brand: "Land Rover ",
//     model: "Defender",
//     year: 2023,
//     class: "Luks",
//     fuelType: "Benzin",
//     transmission: "Avtomat",
//     engineSize: "3.0",
//     seats: 6,
//     dailyPrice: 450,
//     weeklyPrice: 400,
//     monthlyPrice: 350,
//     deposit: 200,
//     image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
//     images: [
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img2.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img3.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img4.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img5.jpeg",





//     ],
//     features: [
//       "Adaptive Cruise Control",
//       "Back-Up Camera",
//       "Dual-Zone Automatic Climate Control",
//       "Lane Departure Warning",
//     ],

//     rules: {
//       minimumAge: 22,
//       drivingExperience: 2,
//       passportRequired: true,
//       licenseRequired: true,
//     },
//     // New enhanced fields
//     category: ["SUV","Luxury"],
//     popularity: 100,
//     availability: true,
//     gallery: [
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img2.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img3.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img4.jpeg",
// "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img5.jpeg",
//     ],
//     specifications: {
//       engine: "3.0L",
//       horsepower: 181,
//       acceleration: "0-100 km/h in 8.9s",
//       topSpeed: 260,
//       fuelConsumption: "1.4L/100km",
//     },
//   },
  {
    id: "24",
    brand: "Land Rover ",
    model: "Defender",
    year: 2023,
    class: "SUV",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "3.0",
    seats: 6,
    dailyPrice: 450,
    weeklyPrice: 400,
    monthlyPrice: 350,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img5.jpeg",





    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Luxury"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/defender/img5.jpeg",
    ],
    specifications: {
      engine: "3.0L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 260,
      fuelConsumption: "1.4L/100km",
    },
  },
  {
    id: "25",
    brand: "Hyundai  ",
    model: "Elantra",
    year: 2022,
    class: "Ecomomy",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "1.6",
    seats:5,
    dailyPrice: 75,
    weeklyPrice: 70,
    monthlyPrice: 60,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img1.jpg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img5.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img6.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img7.jpg",


    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Luxury"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img5.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img6.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/elantra2022/img7.jpg",
    ],
    specifications: {
      engine: "1.6L",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 260,
      fuelConsumption: "1.4L/100km",
    },
  },
  {
    id: "26",
    brand: "Kia",
    model: "Carnival",
    year: 2023,
    class: "Ecomomy",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.2",
    seats:7,
    dailyPrice: 350,
    weeklyPrice: 300,
    monthlyPrice: 250,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img1.jpeg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img5.jpeg",



    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["Minivan","Biznes"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img1.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img2.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img3.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img4.jpeg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiakarnival/img5.jpeg",
    ],
    specifications: {
      engine: "2.2",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 260,
      fuelConsumption: "4.5/100km",
    },
  },
  {
    id: "27",
    brand: "Kia",
    model: "Sportage",
    year: 2023,
    class: "Ecomomy",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.0",
    seats:5,
    dailyPrice: 120,
    weeklyPrice: 100,
    monthlyPrice: 80,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img1.jpg",
    images: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img1.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img2.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img3.jpg',
    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],

    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Ekonom"],
    popularity: 100,
    availability: true,
    gallery: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img1.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img2.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/kiasportage/img3.jpg',
    ],
    specifications: {
      engine: "2.0",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 260,
      fuelConsumption: "4.5/100km",
    },
  },
  {
    id: "28",
    brand: "Land Rover",
    model: "Discovery",
    year: 2017,
    class: "Suv",
    fuelType: "Benzin",
    transmission: "Avtomat",
    engineSize: "2.0",
    seats:5,
    dailyPrice: 100,
    weeklyPrice: 90,
    monthlyPrice: 80,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img9.jpeg",
    images: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img9.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img8.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img10.jpeg',
    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Biznes"],
    popularity: 100,
    availability: true,
    gallery: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img9.jpeg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img8.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/landdiscovery/img10.jpeg',
    ],
    specifications: {
      engine: "2.0",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 230,
      fuelConsumption: "4.5/100km",
    },
  },
  {
    id: "29",
    brand: "Lexus",
    model: " ES 300h",
    year: 2023,
    class: "Sedan",
    fuelType: "Hibrid",
    transmission: "Avtomat",
    engineSize: "2.5",
    seats:5,
    dailyPrice: 140,
    weeklyPrice: 120,
    monthlyPrice: 100,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img1.jpg",
    images: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img1.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img2.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img3.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img4.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img5.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img6.jpg',


    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Biznes"],
    popularity: 100,
    availability: true,
    gallery: [
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img1.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img2.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img3.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img4.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img5.jpg',
'https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/lexuss300h/img6.jpg',
    ],
    specifications: {
      engine: "2.0",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 230,
      fuelConsumption: "4.5/100km",
    },
  },
  {
    id: "30",
    brand: "Li Auto",
    model: " L7",
    year: 2025,
    class: "Biznes",
    fuelType: "Hibrid",
    transmission: "Avtomat",
    engineSize: "1.5",
    seats:6,
    dailyPrice: 140,
    weeklyPrice: 120,
    monthlyPrice: 100,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img5.jpg",




    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Biznes"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img5.jpg",
    ],
    specifications: {
      engine: "2.0",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 230,
      fuelConsumption: "4.5/100km",
    },
  },
  {
    id: "31",
    brand: "Li Auto",
    model: " L7",
    year: 2025,
    class: "Biznes",
    fuelType: "Hibrid",
    transmission: "Avtomat",
    engineSize: "1.5",
    seats:6,
    dailyPrice: 140,
    weeklyPrice: 120,
    monthlyPrice: 100,
    deposit: 200,
    image: "https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
    images: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img5.jpg",




    ],
    features: [
      "Adaptive Cruise Control",
      "Back-Up Camera",
      "Dual-Zone Automatic Climate Control",
      "Lane Departure Warning",
    ],
    rules: {
      minimumAge: 22,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
    },
    // New enhanced fields
    category: ["SUV","Biznes"],
    popularity: 100,
    availability: true,
    gallery: [
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img1.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img2.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img3.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img4.jpg",
"https://exqjgmrrgwsvfklyzyga.supabase.co/storage/v1/object/public/car-images/li/img5.jpg",
    ],
    specifications: {
      engine: "2.0",
      horsepower: 181,
      acceleration: "0-100 km/h in 8.9s",
      topSpeed: 230,
      fuelConsumption: "4.5/100km",
    },
  },
];

// Keep original cars array for backward compatibility
export const cars: Car[] = enhancedCars.map((car) => {
  const {
    category,
    popularity,
    availability,
    gallery,
    specifications,
    ...originalCar
  } = car;
  return originalCar;
});

export const locations: Location[] = [
  { id: "office", name: "Ofisimizdən götürülmə", extraCharge: 0 },
  { id: "airport", name: "Heydər Əliyev Hava Limanı", extraCharge: 43 },
  { id: "city-center", name: "Şəhər Mərkəzi", extraCharge: 26 },
  { id: "hotel", name: "Otel/Yaşayış yeri", extraCharge: 34 },
  { id: "station", name: "Dəmir yolu vağzalı", extraCharge: 31 },
];

export const additionalServices: AdditionalService[] = [
  {
    id: "Driver",
    name: "Şəxsi Sürücü",
    price: 30,
    description: "Təcrübəli sürücü ilə rahat səyahət",
  },
  {
    id: "child-seat",
    name: "Uşaq Oturacağı",
    price: 10,
    description: "0-12 yaş arası uşaqlar üçün təhlükəsiz oturacaq",
  },
  {
    id: "gps",
    name: "GPS Naviqasiya",
    price: 10,
    description: "Peşəkar GPS cihazı",
  },
  {
    id: "insurance",
    name: "Tam Sığorta",
    price: 20,
    description: "Genişləndirilmiş sığorta təminatı",
  },
];

// Enhanced buses data with new fields
export const enhancedBuses: EnhancedBus[] = [
  {
    id: "bus1",
    brand: "MAN Truck",
    model: "Neoplan",
    year: 2015,
    type: "Coach",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.1L",
    capacity: 48,
    dailyPrice: 150,
    weeklyPrice: 130,
    monthlyPrice: 110,
    deposit: 300,
    image:"/buses/napeleon/img1.jpg",
    images: [
      "/buses/napeleon/img1.jpg",
      "/buses/napeleon/img2.jpg",
      "/buses/napeleon/img3.jpg",
      "/buses/napeleon/img4.jpg",
      "/buses/napeleon/img5.jpg",
      "/buses/napeleon/img6.jpg",
      "/buses/napeleon/img7.jpg",

    ],
    features: [
      "Kondisioner",
      "Wi-Fi",
      "USB Şarj Portları",
      "Komfortlu Oturacaqlar",
      "Səs Sistemi",
      "Arxa Kamera"
    ],
    rules: {
      minimumAge: 25,
      drivingExperience: 3,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: true,
    },
    category: ["Minibus"],
    popularity: 88,
    availability: true,
    gallery: [
      "/buses/napeleon/img1.jpg",
      "/buses/napeleon/img2.jpg",
      "/buses/napeleon/img3.jpg",
      "/buses/napeleon/img4.jpg",
      "/buses/napeleon/img5.jpg",
      "/buses/napeleon/img6.jpg",
      "/buses/napeleon/img7.jpg",
    ],
    specifications: {
      engine: "10.5L CDI Diesel",
      horsepower: 400,
      acceleration: "0-100 km/h in 12.5s",
      topSpeed: 160,
      fuelConsumption: "8.5L/100km",
    },
    amenities: ["Wi-Fi", "AC", "USB Charging", "Audio System"],
    routes: ["Şəhərdaxili", "Hava Limanı", "Tur Xidməti"]
  },
  {
    id: "bus2",
    brand: "TEMSA",
    model: "HD C12 ",
    year: 2015,
    type: "Coach",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "10.7L",
    capacity: 49,
    dailyPrice: 300,
    weeklyPrice: 280,
    monthlyPrice: 250,
    deposit: 500,
    image: "/buses/tourismo/img1.jpg",
    images: [
      "/buses/temsa/img1.jpg",
      "/buses/temsa/img2.jpg",
      "/buses/temsa/img3.jpg",
      "/buses/temsa/img4.jpg",
    ],
    features: [
      "Kondisioner",
      "Wi-Fi",
      "WC",
      "Mətbəx",
      "TV/DVD",
      "Yataq Yerləri",
      "Panorama Şüşələr",
      "Premium Oturacaqlar"
    ],
    rules: {
      minimumAge: 25,
      drivingExperience: 5,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: true,
    },
    category: ["Coach", "Tour Bus", "Luxury Bus"],
    popularity: 95,
    availability: true,
    gallery: [
      "/buses/tourismo/img1.jpg",
      "/buses/tourismo/img2.jpg",
      "/buses/tourismo/img3.jpg",
      "/buses/tourismo/img4.jpg",
      "/buses/tourismo/img5.jpg",
    ],
    specifications: {
      engine: "10.7L OM 470 Diesel",
      horsepower: 428,
      acceleration: "0-100 km/h in 18.2s",
      topSpeed: 120,
      fuelConsumption: "28L/100km",
    },
    amenities: ["Wi-Fi", "AC", "Toilet", "Kitchen", "TV/DVD", "Sleeping Berths"],
    routes: ["Şəhərlərarası", "Beynəlxalq Turlar", "Uzun Məsafə"]
  },
  {
    id: "bus3",
    brand: "Iveco",
    model: "Daily",
    year: 2023,
    type: "Minibus",
    fuelType: "Dizel",
    transmission: "Mexaniki",
    engineSize: "3.0L",
    capacity: 25,
    dailyPrice: 180,
    weeklyPrice: 160,
    monthlyPrice: 140,
    deposit: 350,
    image: "/buses/iveco/img1.jpg",
    images: [
      "/buses/iveco/img1.jpg",
      "/buses/iveco/img2.jpg",
      "/buses/iveco/img3.jpg",
      "/buses/iveco/img4.jpg",
    ],
    features: [
      "Kondisioner",
      "USB Şarj Portları",
      "Komfortlu Oturacaqlar",
      "Səs Sistemi",
      "Arxa Park Sensorları",
      "ESP Sistemi"
    ],
    rules: {
      minimumAge: 25,
      drivingExperience: 3,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: true,
    },
    category: ["Minibus"],
    popularity: 82,
    availability: true,
    gallery: [
      "/buses/iveco/img1.jpg",
      "/buses/iveco/img2.jpg",
      "/buses/iveco/img3.jpg",
      "/buses/iveco/img4.jpg",
    ],
    specifications: {
      engine: "3.0L F1C Diesel",
      horsepower: 170,
      acceleration: "0-100 km/h in 14.8s",
      topSpeed: 150,
      fuelConsumption: "9.2L/100km",
    },
    amenities: ["AC", "USB Charging", "Audio System"],
    routes: ["Şəhərdaxili", "Qısa Məsafə Turlar", "Korporativ"]
  },
  {
    id: "bus4",
    brand: "Scania",
    model: "Touring",
    year: 2020,
    type: "Coach",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "9.3L",
    capacity: 53,
    dailyPrice: 320,
    weeklyPrice: 300,
    monthlyPrice: 270,
    deposit: 600,
    image: "/buses/scania/img1.jpg",
    images: [
      "/buses/scania/img1.jpg",
      "/buses/scania/img2.jpg",
      "/buses/scania/img3.jpg",
      "/buses/scania/img4.jpg",
    ],
    features: [
      "Kondisioner",
      "Wi-Fi",
      "WC",
      "Mətbəx",
      "TV Sistemləri",
      "Reclining Oturacaqlar",
      "LED İşıqlandırma",
      "Səs İzolyasiyası"
    ],
    rules: {
      minimumAge: 25,
      drivingExperience: 5,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: true,
    },
    category: ["Coach", "Tour Bus"],
    popularity: 90,
    availability: true,
    gallery: [
      "/buses/scania/img1.jpg",
      "/buses/scania/img2.jpg",
      "/buses/scania/img3.jpg",
      "/buses/scania/img4.jpg",
    ],
    specifications: {
      engine: "9.3L DC09 Diesel",
      horsepower: 360,
      acceleration: "0-100 km/h in 20.1s",
      topSpeed: 115,
      fuelConsumption: "26L/100km",
    },
    amenities: ["Wi-Fi", "AC", "Toilet", "Kitchen", "TV Systems", "LED Lighting"],
    routes: ["Şəhərlərarası", "Beynəlxalq", "Lüks Turlar"]
  },
  {
    id: "bus5",
    brand: "Ford",
    model: "Transit",
    year: 2022,
    type: "Minibus",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.0L",
    capacity: 16,
    dailyPrice: 120,
    weeklyPrice: 100,
    monthlyPrice: 85,
    deposit: 250,
    image: "/buses/transit/img1.jpg",
    images: [
      "/buses/transit/img1.jpg",
      "/buses/transit/img2.jpg",
      "/buses/transit/img3.jpg",
    ],
    features: [
      "Kondisioner",
      "Bluetooth",
      "USB Portları",
      "Elektrik Şüşələr",
      "Mərkəzi Kilit",
      "ABS Sistemi"
    ],
    rules: {
      minimumAge: 23,
      drivingExperience: 2,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: false,
    },
    category: ["Minibus"],
    popularity: 75,
    availability: true,
    gallery: [
      "/buses/transit/img1.jpg",
      "/buses/transit/img2.jpg",
      "/buses/transit/img3.jpg",
    ],
    specifications: {
      engine: "2.0L EcoBlue Diesel",
      horsepower: 130,
      acceleration: "0-100 km/h in 13.2s",
      topSpeed: 145,
      fuelConsumption: "7.8L/100km",
    },
    amenities: ["AC", "Bluetooth", "USB Charging"],
    routes: ["Şəhərdaxili", "Hava Limanı", "Kiçik Qrup Turları"]
  },
  {
    id: "bus6",
    brand: "Volkswagen",
    model: "Crafter",
    year: 2023,
    type: "Minibus",
    fuelType: "Dizel",
    transmission: "Avtomat",
    engineSize: "2.0L",
    capacity: 22,
    dailyPrice: 160,
    weeklyPrice: 140,
    monthlyPrice: 120,
    deposit: 300,
    image: "/buses/crafter/img1.jpg",
    images: [
      "/buses/crafter/img1.jpg",
      "/buses/crafter/img2.jpg",
      "/buses/crafter/img3.jpg",
      "/buses/crafter/img4.jpg",
    ],
    features: [
      "Kondisioner",
      "Wi-Fi",
      "USB Şarj",
      "Komfortlu Oturacaqlar",
      "Səs Sistemi",
      "Panorama Şüşələr",
      "LED İşıqlar"
    ],
    rules: {
      minimumAge: 25,
      drivingExperience: 3,
      passportRequired: true,
      licenseRequired: true,
      commercialLicense: true,
    },
    category: ["Minibus"],
    popularity: 85,
    availability: true,
    gallery: [
      "/buses/crafter/img1.jpg",
      "/buses/crafter/img2.jpg",
      "/buses/crafter/img3.jpg",
      "/buses/crafter/img4.jpg",
    ],
    specifications: {
      engine: "2.0L TDI Diesel",
      horsepower: 177,
      acceleration: "0-100 km/h in 11.8s",
      topSpeed: 155,
      fuelConsumption: "8.1L/100km",
    },
    amenities: ["Wi-Fi", "AC", "USB Charging", "Audio System", "LED Lighting"],
    routes: ["Şəhərdaxili", "Orta Məsafə", "Korporativ Xidmət"]
  }
];

// Keep original buses array for backward compatibility
export const buses: Bus[] = enhancedBuses.map((bus) => {
  const {
    category,
    popularity,
    availability,
    gallery,
    specifications,
    amenities,
    routes,
    ...originalBus
  } = bus;
  return originalBus;
});

export const customerReviews: CustomerReview[] = [
  {
    id: "1",
    customerName: "Əli Məmmədov",
    rating: 5,
    reviewText:
      "Çox yaxşı xidmət! Maşın təmiz və yaxşı vəziyyətdə idi. Heyət çox köməkçi oldu.",
    date: "2024-01-15",
    carRented: "Toyota Camry",
    verified: true,
    helpful: 12,
    source: "google",
  },
  {
    id: "2",
    customerName: "Leyla Həsənova",
    rating: 5,
    reviewText:
      "Mükəmməl təcrübə! Rezervasiya prosesi çox asan idi və maşın vaxtında təhvil verildi.",
    date: "2024-01-10",
    carRented: "BMW X5",
    verified: true,
    helpful: 8,
    source: "google",
  },
  {
    id: "3",
    customerName: "Rəşad Əliyev",
    rating: 4,
    reviewText: "Yaxşı qiymətlər və keyfiyyətli maşınlar. Tövsiyə edirəm!",
    date: "2024-01-08",
    carRented: "Hyundai Elantra",
    verified: true,
    helpful: 6,
    source: "internal",
  },
  {
    id: "4",
    customerName: "Günel Qasımova",
    rating: 5,
    reviewText:
      "Hər şey mükəmməl idi. Maşın çox rahat və təmiz idi. Mütləq yenidən istifadə edəcəyəm.",
    date: "2024-01-05",
    carRented: "Mercedes E-Class",
    verified: true,
    helpful: 15,
    source: "google",
  },
  {
    id: "5",
    customerName: "Orxan Babayev",
    rating: 4,
    reviewText:
      "Peşəkar xidmət və ədalətli qiymətlər. Kiçik gecikmə oldu, amma ümumiyyətlə məmnunam.",
    date: "2024-01-03",
    carRented: "Volkswagen Passat",
    verified: true,
    helpful: 4,
    source: "internal",
  },
  {
    id: "6",
    customerName: "Səbinə Rəhimova",
    rating: 5,
    reviewText:
      "Çox yaxşı təcrübə! Heyət çox mehriban və köməkçi idi. Maşın da əla vəziyyətdə idi.",
    date: "2023-12-28",
    carRented: "Kia Sportage",
    verified: true,
    helpful: 9,
    source: "google",
  },
  {
    id: "7",
    customerName: "Elvin Nərimanov",
    rating: 5,
    reviewText:
      "Mükəmməl xidmət! Sürətli rezervasiya və problemsiz təhvil alma prosesi.",
    date: "2023-12-25",
    carRented: "Toyota Camry",
    verified: true,
    helpful: 11,
    source: "facebook",
  },
  {
    id: "8",
    customerName: "Aynur Sultanova",
    rating: 4,
    reviewText:
      "Yaxşı qiymət-keyfiyyət nisbəti. Maşın təmiz və yanacaq dolu idi.",
    date: "2023-12-20",
    carRented: "Hyundai Elantra",
    verified: true,
    helpful: 7,
    source: "google",
  },
  {
    id: "9",
    customerName: "Fərid Quliyev",
    rating: 5,
    reviewText:
      "Bakıda ən yaxşı rent a car şirkəti! BMW-ni 3 gün icarəyə götürdüm, hər şey mükəmməl idi.",
    date: "2023-12-18",
    carRented: "BMW 3 Series",
    verified: true,
    helpful: 13,
    source: "google",
  },
  {
    id: "10",
    customerName: "Nigar Əhmədova",
    rating: 5,
    reviewText:
      "Ailə səfəri üçün 7 nəfərlik maşın icarəyə götürdük. Çox rahat və təmiz idi. Uşaqlar çox sevdi!",
    date: "2023-12-15",
    carRented: "Toyota Highlander",
    verified: true,
    helpful: 18,
    source: "google",
  },
  {
    id: "11",
    customerName: "Kamran Vəliyev",
    rating: 4,
    reviewText:
      "İş səfəri üçün istifadə etdim. Maşın yaxşı idi, yalnız təhvil alma yerində kiçik gözləmə oldu.",
    date: "2023-12-12",
    carRented: "Audi A4",
    verified: true,
    helpful: 5,
    source: "internal",
  },
  {
    id: "12",
    customerName: "Zeynəb Məhərrəmova",
    rating: 5,
    reviewText:
      "Hava limanından birbaşa maşın aldım. Çox sürətli və peşəkar xidmət. Təşəkkür edirəm!",
    date: "2023-12-10",
    carRented: "Hyundai Tucson",
    verified: true,
    helpful: 14,
    source: "google",
  },
  {
    id: "13",
    customerName: "Tural İbrahimov",
    rating: 5,
    reviewText:
      "Toy mərasimi üçün lüks maşın icarəyə götürdük. Mercedes çox gözəl və təmiz idi. Hamı bəyəndi!",
    date: "2023-12-08",
    carRented: "Mercedes S-Class",
    verified: true,
    helpful: 22,
    source: "google",
  },
  {
    id: "14",
    customerName: "Aysel Nəbiyeva",
    rating: 4,
    reviewText:
      "Qiymətlər münasibdir və maşınlar yaxşı vəziyyətdədir. Növbəti dəfə yenə burada icarəyə götürəcəyəm.",
    date: "2023-12-05",
    carRented: "Kia Cerato",
    verified: true,
    helpful: 8,
    source: "facebook",
  },
  {
    id: "15",
    customerName: "Ramin Həsənov",
    rating: 5,
    reviewText:
      "24/7 dəstək xidməti çox yaxşıdır. Gecə yarısı problem oldu, dərhal kömək etdilər.",
    date: "2023-12-03",
    carRented: "Toyota Corolla",
    verified: true,
    helpful: 16,
    source: "google",
  },
  {
    id: "16",
    customerName: "Səadət Əliyeva",
    rating: 5,
    reviewText:
      "Qadın sürücü olaraq özümü çox təhlükəsiz hiss etdim. Maşın yeni və texniki vəziyyəti əladır.",
    date: "2023-12-01",
    carRented: "Nissan Qashqai",
    verified: true,
    helpful: 19,
    source: "google",
  },
  {
    id: "17",
    customerName: "Elçin Məmmədov",
    rating: 4,
    reviewText:
      "Şəhərdaxili səfərlər üçün ideal. Yanacaq sərfiyyatı azdır və park etmək asandır.",
    date: "2023-11-28",
    carRented: "Chevrolet Spark",
    verified: true,
    helpful: 7,
    source: "internal",
  },
  {
    id: "18",
    customerName: "Gülnar Rəsulova",
    rating: 5,
    reviewText:
      "Dostlarımla Qəbələyə səfər etdik. SUV maşın dağ yolları üçün mükəmməl idi!",
    date: "2023-11-25",
    carRented: "Ford Explorer",
    verified: true,
    helpful: 12,
    source: "google",
  },
  {
    id: "19",
    customerName: "Vüsal Əsgərov",
    rating: 5,
    reviewText:
      "Online rezervasiya sistemi çox rahatdır. Evdən çıxmadan maşın sifariş verdim.",
    date: "2023-11-22",
    carRented: "Volkswagen Golf",
    verified: true,
    helpful: 10,
    source: "google",
  },
  {
    id: "20",
    customerName: "Könül Həmidova",
    rating: 4,
    reviewText:
      "Qiymətlər digər şirkətlərdən daha sərfəlidir. Maşın da yaxşı vəziyyətdə idi.",
    date: "2023-11-20",
    carRented: "Renault Logan",
    verified: true,
    helpful: 6,
    source: "facebook",
  },
  {
    id: "21",
    customerName: "Əkbər Nağıyev",
    rating: 5,
    reviewText:
      "Biznes səfəri üçün premium maşın götürdüm. Müştərilərim çox təsirləndi. Təşəkkür edirəm!",
    date: "2023-11-18",
    carRented: "BMW 5 Series",
    verified: true,
    helpful: 15,
    source: "google",
  },
  {
    id: "22",
    customerName: "Lalə Əliz adə",
    rating: 5,
    reviewText:
      "Hamilə olduğum üçün rahat maşın lazım idi. Crossover mükəmməl seçim oldu!",
    date: "2023-11-15",
    carRented: "Mazda CX-5",
    verified: true,
    helpful: 17,
    source: "google",
  },
  {
    id: "23",
    customerName: "Rəşid Bayramov",
    rating: 4,
    reviewText:
      "Uzun müddətli icarə üçün endirim tətbiq etdilər. Çox məmnunam, tövsiyə edirəm.",
    date: "2023-11-12",
    carRented: "Honda Civic",
    verified: true,
    helpful: 9,
    source: "internal",
  },
  {
    id: "24",
    customerName: "Şəbnəm Qədirzadə",
    rating: 5,
    reviewText:
      "Hava limanına çatdırma xidməti mövcuddur. Çox rahatdır, vaxt itirmirsən.",
    date: "2023-11-10",
    carRented: "Skoda Octavia",
    verified: true,
    helpful: 11,
    source: "google",
  },
  {
    id: "25",
    customerName: "Mübariz Əhmədov",
    rating: 5,
    reviewText:
      "Maşının sığortası tam idi. Kiçik bir cızıq oldu, heç problem olmadı. Çox peşəkar yanaşma!",
    date: "2023-11-08",
    carRented: "Peugeot 308",
    verified: true,
    helpful: 13,
    source: "google",
  },
  {
    id: "26",
    customerName: "Arzu Məhəmmədova",
    rating: 4,
    reviewText:
      "Ailə dostu şirkətdir. Uşaq oturacağı da təmin etdilər. Çox düşüncəli!",
    date: "2023-11-05",
    carRented: "Opel Astra",
    verified: true,
    helpful: 8,
    source: "facebook",
  },
  {
    id: "27",
    customerName: "Samir Hüseynov",
    rating: 5,
    reviewText:
      "Elektrik maşın icarəyə götürdüm. Çox sakit və iqtisadlıdır. Gələcəyin maşınları!",
    date: "2023-11-03",
    carRented: "Tesla Model 3",
    verified: true,
    helpful: 21,
    source: "google",
  },
  {
    id: "28",
    customerName: "Gülay Əliyeva",
    rating: 5,
    reviewText:
      "Şəhər mərkəzində ofisləri var, çox rahatdır. Heyət çox mehriban və köməkçidir.",
    date: "2023-11-01",
    carRented: "Fiat Tipo",
    verified: true,
    helpful: 14,
    source: "google",
  },
  {
    id: "29",
    customerName: "Rövşən Məmmədli",
    rating: 4,
    reviewText:
      "Qış təkərləri ilə təmin etdilər. Qarlı havada heç problem olmadı. Çox düşüncəli!",
    date: "2023-10-28",
    carRented: "Subaru Forester",
    verified: true,
    helpful: 12,
    source: "internal",
  },
  {
    id: "30",
    customerName: "Aytən Rəhimova",
    rating: 5,
    reviewText:
      "İlk dəfə maşın icarəyə götürürdüm. Hər şeyi ətraflı izah etdilər. Çox minnətdaram!",
    date: "2023-10-25",
    carRented: "Dacia Sandero",
    verified: true,
    helpful: 16,
    source: "google",
  },
];

// Certificates data structure
export const certificates: Certificate[] = [
  {
    id: "1",
    title: "ISO 9001:2015 Keyfiyyət İdarəetmə Sistemi",
    image: "/certificates/img1.jpg",
    description: "Beynəlxalq keyfiyyət standartlarına uyğunluq sertifikatı",
    issueDate: "2023-06-15",
    validUntil: "2026-06-15",
    issuer: "TÜV SÜD",
    credentialId: "ISO-9001-2023-AZ-001",
  },
  {
    id: "2",
    title: "Avtomobil İcarəsi Lisenziyası",
    image: "/certificates/img2.jpg",
    description: "Azərbaycan Respublikası Nəqliyyat Nazirliyi tərəfindən verilmiş rəsmi lisenziya",
    issueDate: "2023-01-10",
    validUntil: "2028-01-10",
    issuer: "Nəqliyyat Nazirliyi",
    credentialId: "RNT-2023-001-AZ",
  },
  {
    id: "3",
    title: "Sığorta Sertifikatı",
    image: "/certificates/img3.jpg",
    description: "Tam sığorta təminatı sertifikatı",
    issueDate: "2024-01-01",
    validUntil: "2024-12-31",
    issuer: "ASCO Sığorta",
    credentialId: "ASCO-2024-RS-789",
  },
  {
    id: "4",
    title: "Müştəri Məmnuniyyəti Mükafatı",
    image: "/certificates/img4.jpg",
    description: "2023-cü il üçün ən yaxşı müştəri xidməti mükafatı",
    issueDate: "2023-12-01",
    issuer: "Azərbaycan Turizm Assosiasiyası",
    credentialId: "ATA-2023-CS-AWARD",
  },
  {
    id: "5",
    title: "Yol Hərəkəti Təhlükəsizliyi Sertifikatı",
    image: "/certificates/img5.jpg",
    description: "Yol hərəkəti təhlükəsizliyi standartlarına uyğunluq sertifikatı",
    issueDate: "2024-03-15",
    validUntil: "2027-03-15",
    issuer: "Yol Hərəkəti Təhlükəsizliyi Agentliyi",
    credentialId: "YHTA-2024-SAFETY-123",
  },
  {
    id: "6",
    title: "Turizm Xidmətləri Lisenziyası",
    image: "/certificates/img6.jpg",
    description: "Turizm və səyahət xidmətləri göstərmək üçün rəsmi lisenziya",
    issueDate: "2023-08-20",
    validUntil: "2028-08-20",
    issuer: "Turizm Nazirliyi",
    credentialId: "TUR-2023-LIC-456",
  },
  {
    id: "7",
    title: "Texniki Baxış Sertifikatı",
    image: "/certificates/img7.jpg",
    description: "Avtomobil parkının texniki vəziyyətinin təsdiqi sertifikatı",
    issueDate: "2024-02-10",
    validUntil: "2025-02-10",
    issuer: "Texniki Baxış Mərkəzi",
    credentialId: "TBM-2024-FLEET-789",
  },
  {
    id: "8",
    title: "Peşəkar Sürücü Təlimi Sertifikatı",
    image: "/certificates/img8.jpg",
    description: "Peşəkar sürücü təlimi və sertifikatlaşdırma proqramı",
    issueDate: "2023-11-05",
    validUntil: "2026-11-05",
    issuer: "Sürücü Təlimi Mərkəzi",
    credentialId: "STM-2023-PROF-321",
  },
  {
    id: "9",
    title: "Yanacaq Səmərəliliyi Sertifikatı",
    image: "/certificates/img9.jpg",
    description: "Yanacaq səmərəliliyi və ekoloji standartlar sertifikatı",
    issueDate: "2024-01-20",
    validUntil: "2026-01-20",
    issuer: "Ətraf Mühit Nazirliyi",
    credentialId: "AMN-2024-FUEL-654",
  },
  {
    id: "10",
    title: "Müştəri Xidmətləri Keyfiyyət Sertifikatı",
    image: "/certificates/img10.jpg",
    description: "Müştəri xidmətləri keyfiyyət standartları sertifikatı",
    issueDate: "2023-10-15",
    validUntil: "2025-10-15",
    issuer: "Keyfiyyət Təminatı Mərkəzi",
    credentialId: "KTM-2023-CS-987",
  },
  {
    id: "11",
    title: "Rəqəmsal Xidmətlər Sertifikatı",
    image: "/certificates/img11.jpg",
    description: "Rəqəmsal platformalar və onlayn xidmətlər sertifikatı",
    issueDate: "2024-04-10",
    validUntil: "2027-04-10",
    issuer: "Rəqəmsal İnkişaf Nazirliyi",
    credentialId: "RIN-2024-DIGITAL-147",
  },
  {
    id: "12",
    title: "Beynəlxalq Xidmət Standartları Sertifikatı",
    image: "/certificates/img12.jpg",
    description: "Beynəlxalq səviyyədə xidmət keyfiyyəti standartları",
    issueDate: "2023-12-20",
    validUntil: "2026-12-20",
    issuer: "Beynəlxalq Sertifikatlaşdırma Orqanı",
    credentialId: "BSO-2023-INTL-258",
  },
];

// Base car categories for navigation dropdown
const baseCategoriesData: Omit<CarCategory, "count">[] = [
  {
    id: "economy",
    name: "economy",
    displayName: "Ekonom",
    icon: "🚗",
    description: "Sərfəli və praktik seçimlər",
  },
  {
    id: "business",
    name: "business",
    displayName: "Biznes",
    icon: "🚘",
    description: "İş səfərləri üçün ideal",
  },
  {
    id: "suv",
    name: "suv",
    displayName: "SUV",
    icon: "🚐",
    description: "Yüksək və güclü maşınlar",
  },
  {
    id: "sedan",
    name: "sedan",
    displayName: "Sedan",
    icon: "🚙",
    description: "Klassik və rahat maşınlar",
  },
  {
    id: "hatchback",
    name: "hatchback",
    displayName: "Hatchback",
    icon: "🚗",
    description: "Kompakt və çevik maşınlar",
  },
  {
    id: "minivan",
    name: "minivan",
    displayName: "Minivan",
    icon: "🚌",
    description: "Böyük ailələr üçün geniş salon",
  },
  {
    id: "luxury",
    name: "luxury",
    displayName: "Lüks",
    icon: "🏎️",
    description: "Premium təcrübə",
  },
];

// Function to calculate category counts
function calculateCategoryCounts(): CarCategory[] {
  const categoryCounts: Record<string, number> = {};

  // Count cars in each category
  enhancedCars.forEach((car) => {
    if (car.category) {
      car.category.forEach(cat => {
        categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
      });
    }
  });

  // Map base categories with calculated counts
  return baseCategoriesData.map((category) => ({
    ...category,
    count: categoryCounts[category.displayName] || 0,
  }));
}

// Car categories for navigation dropdown with dynamic counts
export const carCategories: CarCategory[] = calculateCategoryCounts();
